version: '3'

services:
  db:
    image: postgres:11
    container_name: postgres
    restart: always
    build: ./database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=pika_prep
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgresql:/var/lib/postgresql/data:nocopy
      - postgresql_data:/var/lib/postgresql/data:nocopy

  backend:
    container_name: backend
    build: ./backend
    image: tornado
    volumes:
     - ./backend:/var/www/backend
    depends_on:
      - "db"
    ports:
      - 8888:8888
      - 8889:8889
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgres://myuser:mypassword@postgres:5432/pika_prep
      - JWT_SECRET=my_secret_key

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/var/www/frontend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development

volumes:
  postgresql:
  postgresql_data: