version: '3'

services:
  backend:
    container_name: backend
    build: ./backend
    image: tornado
    volumes:
     - ./backend:/var/www/backend
    ports:
      - 8888:8888
    environment:
      - APP_ENV=dev

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/var/www/frontend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development

  db:
    image: postgres:11
    container_name: postgres
    restart: always
    build:
      context: ./database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=pika_prep
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgresql:/var/lib/postgresql/data
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql:
  postgresql_data: