version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      # TODO: replace these
      IMAGE_NAME: REPO/IMAGE_NAME
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Client image
          command: |
            docker build -t $CLIENT_IMAGE_NAME:latest .
      - run:
          name: Build Server image
          command: |
            docker build -t $SERVER_IMAGE_NAME:latest .
      - run:
          name: Push Client Image
          command: |
            echo "$REPO_PASS" | docker login -u "$REPO_USERNAME" --password-stdin
            docker push $CLIENT_IMAGE_NAME:latest
      - run:
          name: Push Server Image
          command: |
            echo "$REPO_PASS" | docker login -u "$REPO_USERNAME" --password-stdin
            docker push $SERVER_IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
